<template>
  <div>
    <div
        class="index-board-item"
        v-for="(item, index) in relic"
        :key="index"
    >
      <div>
        <img :src="item.img_url" alt="">
      </div>
      <div class="index-board-button">
        <router-link :to="'/details/'+item.img_url" class="button">文物详情</router-link>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      relic: [
        {"id": "157", "title": "Vase with the Eight Daoist Immortals", "dated": "c. 1300", "artist": "", "role": "Artist", "department": "Asian Art", "medium": "Longquan ware Porcelain with celadon glaze over impressed designs", "country": "China", "description": "Longquan ware; celadon glaze with 8 unglazed cartouches carved with immortals; floral cartouches above and below each immortal; low foot, narrow mouth", "comments": "This ovoid vase has an octagonal cross section and each of the eight sides comprising the vessel is decorated with molded recessed panels depicting one of the Eight Daoist Immortals amidst two floral sprays. The images of the immortals are shown standing on drifting clouds and each carry their identifying attributes.\r\nA wax resist technique was employed in the decoration of this piece. The central panels were painted with wax before glazing to prevent the celadon glaze from adhering to those areas. Upon firing, the unglazed portions of the clay body burned a bright rust color due to iron compounds in the clay.", "web_url": "https://collections.artsmia.org/art/157", "img_url": "https://6.api.artsmia.org/157.jpg", "submit_time": "2023-04-11 13:11:01"},
        {"id": "157", "title": "Vase with the Eight Daoist Immortals", "dated": "c. 1300", "artist": "", "role": "Artist", "department": "Asian Art", "medium": "Longquan ware Porcelain with celadon glaze over impressed designs", "country": "China", "description": "Longquan ware; celadon glaze with 8 unglazed cartouches carved with immortals; floral cartouches above and below each immortal; low foot, narrow mouth", "comments": "This ovoid vase has an octagonal cross section and each of the eight sides comprising the vessel is decorated with molded recessed panels depicting one of the Eight Daoist Immortals amidst two floral sprays. The images of the immortals are shown standing on drifting clouds and each carry their identifying attributes.\r\nA wax resist technique was employed in the decoration of this piece. The central panels were painted with wax before glazing to prevent the celadon glaze from adhering to those areas. Upon firing, the unglazed portions of the clay body burned a bright rust color due to iron compounds in the clay.", "web_url": "https://collections.artsmia.org/art/157", "img_url": "https://6.api.artsmia.org/157.jpg", "submit_time": "2023-04-11 13:11:01"},
        {"id": "157", "title": "Vase with the Eight Daoist Immortals", "dated": "c. 1300", "artist": "", "role": "Artist", "department": "Asian Art", "medium": "Longquan ware Porcelain with celadon glaze over impressed designs", "country": "China", "description": "Longquan ware; celadon glaze with 8 unglazed cartouches carved with immortals; floral cartouches above and below each immortal; low foot, narrow mouth", "comments": "This ovoid vase has an octagonal cross section and each of the eight sides comprising the vessel is decorated with molded recessed panels depicting one of the Eight Daoist Immortals amidst two floral sprays. The images of the immortals are shown standing on drifting clouds and each carry their identifying attributes.\r\nA wax resist technique was employed in the decoration of this piece. The central panels were painted with wax before glazing to prevent the celadon glaze from adhering to those areas. Upon firing, the unglazed portions of the clay body burned a bright rust color due to iron compounds in the clay.", "web_url": "https://collections.artsmia.org/art/157", "img_url": "https://6.api.artsmia.org/157.jpg", "submit_time": "2023-04-11 13:11:01"},
        {"id": "157", "title": "Vase with the Eight Daoist Immortals", "dated": "c. 1300", "artist": "", "role": "Artist", "department": "Asian Art", "medium": "Longquan ware Porcelain with celadon glaze over impressed designs", "country": "China", "description": "Longquan ware; celadon glaze with 8 unglazed cartouches carved with immortals; floral cartouches above and below each immortal; low foot, narrow mouth", "comments": "This ovoid vase has an octagonal cross section and each of the eight sides comprising the vessel is decorated with molded recessed panels depicting one of the Eight Daoist Immortals amidst two floral sprays. The images of the immortals are shown standing on drifting clouds and each carry their identifying attributes.\r\nA wax resist technique was employed in the decoration of this piece. The central panels were painted with wax before glazing to prevent the celadon glaze from adhering to those areas. Upon firing, the unglazed portions of the clay body burned a bright rust color due to iron compounds in the clay.", "web_url": "https://collections.artsmia.org/art/157", "img_url": "https://6.api.artsmia.org/157.jpg", "submit_time": "2023-04-11 13:11:01"},
        {"id": "157", "title": "Vase with the Eight Daoist Immortals", "dated": "c. 1300", "artist": "", "role": "Artist", "department": "Asian Art", "medium": "Longquan ware Porcelain with celadon glaze over impressed designs", "country": "China", "description": "Longquan ware; celadon glaze with 8 unglazed cartouches carved with immortals; floral cartouches above and below each immortal; low foot, narrow mouth", "comments": "This ovoid vase has an octagonal cross section and each of the eight sides comprising the vessel is decorated with molded recessed panels depicting one of the Eight Daoist Immortals amidst two floral sprays. The images of the immortals are shown standing on drifting clouds and each carry their identifying attributes.\r\nA wax resist technique was employed in the decoration of this piece. The central panels were painted with wax before glazing to prevent the celadon glaze from adhering to those areas. Upon firing, the unglazed portions of the clay body burned a bright rust color due to iron compounds in the clay.", "web_url": "https://collections.artsmia.org/art/157", "img_url": "https://6.api.artsmia.org/157.jpg", "submit_time": "2023-04-11 13:11:01"},
        {"id": "157", "title": "Vase with the Eight Daoist Immortals", "dated": "c. 1300", "artist": "", "role": "Artist", "department": "Asian Art", "medium": "Longquan ware Porcelain with celadon glaze over impressed designs", "country": "China", "description": "Longquan ware; celadon glaze with 8 unglazed cartouches carved with immortals; floral cartouches above and below each immortal; low foot, narrow mouth", "comments": "This ovoid vase has an octagonal cross section and each of the eight sides comprising the vessel is decorated with molded recessed panels depicting one of the Eight Daoist Immortals amidst two floral sprays. The images of the immortals are shown standing on drifting clouds and each carry their identifying attributes.\r\nA wax resist technique was employed in the decoration of this piece. The central panels were painted with wax before glazing to prevent the celadon glaze from adhering to those areas. Upon firing, the unglazed portions of the clay body burned a bright rust color due to iron compounds in the clay.", "web_url": "https://collections.artsmia.org/art/157", "img_url": "https://6.api.artsmia.org/157.jpg", "submit_time": "2023-04-11 13:11:01"},
        {"id": "157", "title": "Vase with the Eight Daoist Immortals", "dated": "c. 1300", "artist": "", "role": "Artist", "department": "Asian Art", "medium": "Longquan ware Porcelain with celadon glaze over impressed designs", "country": "China", "description": "Longquan ware; celadon glaze with 8 unglazed cartouches carved with immortals; floral cartouches above and below each immortal; low foot, narrow mouth", "comments": "This ovoid vase has an octagonal cross section and each of the eight sides comprising the vessel is decorated with molded recessed panels depicting one of the Eight Daoist Immortals amidst two floral sprays. The images of the immortals are shown standing on drifting clouds and each carry their identifying attributes.\r\nA wax resist technique was employed in the decoration of this piece. The central panels were painted with wax before glazing to prevent the celadon glaze from adhering to those areas. Upon firing, the unglazed portions of the clay body burned a bright rust color due to iron compounds in the clay.", "web_url": "https://collections.artsmia.org/art/157", "img_url": "https://6.api.artsmia.org/157.jpg", "submit_time": "2023-04-11 13:11:01"},
        {"id": "157", "title": "Vase with the Eight Daoist Immortals", "dated": "c. 1300", "artist": "", "role": "Artist", "department": "Asian Art", "medium": "Longquan ware Porcelain with celadon glaze over impressed designs", "country": "China", "description": "Longquan ware; celadon glaze with 8 unglazed cartouches carved with immortals; floral cartouches above and below each immortal; low foot, narrow mouth", "comments": "This ovoid vase has an octagonal cross section and each of the eight sides comprising the vessel is decorated with molded recessed panels depicting one of the Eight Daoist Immortals amidst two floral sprays. The images of the immortals are shown standing on drifting clouds and each carry their identifying attributes.\r\nA wax resist technique was employed in the decoration of this piece. The central panels were painted with wax before glazing to prevent the celadon glaze from adhering to those areas. Upon firing, the unglazed portions of the clay body burned a bright rust color due to iron compounds in the clay.", "web_url": "https://collections.artsmia.org/art/157", "img_url": "https://6.api.artsmia.org/157.jpg", "submit_time": "2023-04-11 13:11:01"},
        {"id": "157", "title": "Vase with the Eight Daoist Immortals", "dated": "c. 1300", "artist": "", "role": "Artist", "department": "Asian Art", "medium": "Longquan ware Porcelain with celadon glaze over impressed designs", "country": "China", "description": "Longquan ware; celadon glaze with 8 unglazed cartouches carved with immortals; floral cartouches above and below each immortal; low foot, narrow mouth", "comments": "This ovoid vase has an octagonal cross section and each of the eight sides comprising the vessel is decorated with molded recessed panels depicting one of the Eight Daoist Immortals amidst two floral sprays. The images of the immortals are shown standing on drifting clouds and each carry their identifying attributes.\r\nA wax resist technique was employed in the decoration of this piece. The central panels were painted with wax before glazing to prevent the celadon glaze from adhering to those areas. Upon firing, the unglazed portions of the clay body burned a bright rust color due to iron compounds in the clay.", "web_url": "https://collections.artsmia.org/art/157", "img_url": "https://6.api.artsmia.org/157.jpg", "submit_time": "2023-04-11 13:11:01"},
        {"id": "157", "title": "Vase with the Eight Daoist Immortals", "dated": "c. 1300", "artist": "", "role": "Artist", "department": "Asian Art", "medium": "Longquan ware Porcelain with celadon glaze over impressed designs", "country": "China", "description": "Longquan ware; celadon glaze with 8 unglazed cartouches carved with immortals; floral cartouches above and below each immortal; low foot, narrow mouth", "comments": "This ovoid vase has an octagonal cross section and each of the eight sides comprising the vessel is decorated with molded recessed panels depicting one of the Eight Daoist Immortals amidst two floral sprays. The images of the immortals are shown standing on drifting clouds and each carry their identifying attributes.\r\nA wax resist technique was employed in the decoration of this piece. The central panels were painted with wax before glazing to prevent the celadon glaze from adhering to those areas. Upon firing, the unglazed portions of the clay body burned a bright rust color due to iron compounds in the clay.", "web_url": "https://collections.artsmia.org/art/157", "img_url": "https://6.api.artsmia.org/157.jpg", "submit_time": "2023-04-11 13:11:01"},
        {"id": "157", "title": "Vase with the Eight Daoist Immortals", "dated": "c. 1300", "artist": "", "role": "Artist", "department": "Asian Art", "medium": "Longquan ware Porcelain with celadon glaze over impressed designs", "country": "China", "description": "Longquan ware; celadon glaze with 8 unglazed cartouches carved with immortals; floral cartouches above and below each immortal; low foot, narrow mouth", "comments": "This ovoid vase has an octagonal cross section and each of the eight sides comprising the vessel is decorated with molded recessed panels depicting one of the Eight Daoist Immortals amidst two floral sprays. The images of the immortals are shown standing on drifting clouds and each carry their identifying attributes.\r\nA wax resist technique was employed in the decoration of this piece. The central panels were painted with wax before glazing to prevent the celadon glaze from adhering to those areas. Upon firing, the unglazed portions of the clay body burned a bright rust color due to iron compounds in the clay.", "web_url": "https://collections.artsmia.org/art/157", "img_url": "https://6.api.artsmia.org/157.jpg", "submit_time": "2023-04-11 13:11:01"},
        {"id": "157", "title": "Vase with the Eight Daoist Immortals", "dated": "c. 1300", "artist": "", "role": "Artist", "department": "Asian Art", "medium": "Longquan ware Porcelain with celadon glaze over impressed designs", "country": "China", "description": "Longquan ware; celadon glaze with 8 unglazed cartouches carved with immortals; floral cartouches above and below each immortal; low foot, narrow mouth", "comments": "This ovoid vase has an octagonal cross section and each of the eight sides comprising the vessel is decorated with molded recessed panels depicting one of the Eight Daoist Immortals amidst two floral sprays. The images of the immortals are shown standing on drifting clouds and each carry their identifying attributes.\r\nA wax resist technique was employed in the decoration of this piece. The central panels were painted with wax before glazing to prevent the celadon glaze from adhering to those areas. Upon firing, the unglazed portions of the clay body burned a bright rust color due to iron compounds in the clay.", "web_url": "https://collections.artsmia.org/art/157", "img_url": "https://6.api.artsmia.org/157.jpg", "submit_time": "2023-04-11 13:11:01"},
        {"id": "157", "title": "Vase with the Eight Daoist Immortals", "dated": "c. 1300", "artist": "", "role": "Artist", "department": "Asian Art", "medium": "Longquan ware Porcelain with celadon glaze over impressed designs", "country": "China", "description": "Longquan ware; celadon glaze with 8 unglazed cartouches carved with immortals; floral cartouches above and below each immortal; low foot, narrow mouth", "comments": "This ovoid vase has an octagonal cross section and each of the eight sides comprising the vessel is decorated with molded recessed panels depicting one of the Eight Daoist Immortals amidst two floral sprays. The images of the immortals are shown standing on drifting clouds and each carry their identifying attributes.\r\nA wax resist technique was employed in the decoration of this piece. The central panels were painted with wax before glazing to prevent the celadon glaze from adhering to those areas. Upon firing, the unglazed portions of the clay body burned a bright rust color due to iron compounds in the clay.", "web_url": "https://collections.artsmia.org/art/157", "img_url": "https://6.api.artsmia.org/157.jpg", "submit_time": "2023-04-11 13:11:01"},
        {"id": "157", "title": "Vase with the Eight Daoist Immortals", "dated": "c. 1300", "artist": "", "role": "Artist", "department": "Asian Art", "medium": "Longquan ware Porcelain with celadon glaze over impressed designs", "country": "China", "description": "Longquan ware; celadon glaze with 8 unglazed cartouches carved with immortals; floral cartouches above and below each immortal; low foot, narrow mouth", "comments": "This ovoid vase has an octagonal cross section and each of the eight sides comprising the vessel is decorated with molded recessed panels depicting one of the Eight Daoist Immortals amidst two floral sprays. The images of the immortals are shown standing on drifting clouds and each carry their identifying attributes.\r\nA wax resist technique was employed in the decoration of this piece. The central panels were painted with wax before glazing to prevent the celadon glaze from adhering to those areas. Upon firing, the unglazed portions of the clay body burned a bright rust color due to iron compounds in the clay.", "web_url": "https://collections.artsmia.org/art/157", "img_url": "https://6.api.artsmia.org/157.jpg", "submit_time": "2023-04-11 13:11:01"},
        {"id": "157", "title": "Vase with the Eight Daoist Immortals", "dated": "c. 1300", "artist": "", "role": "Artist", "department": "Asian Art", "medium": "Longquan ware Porcelain with celadon glaze over impressed designs", "country": "China", "description": "Longquan ware; celadon glaze with 8 unglazed cartouches carved with immortals; floral cartouches above and below each immortal; low foot, narrow mouth", "comments": "This ovoid vase has an octagonal cross section and each of the eight sides comprising the vessel is decorated with molded recessed panels depicting one of the Eight Daoist Immortals amidst two floral sprays. The images of the immortals are shown standing on drifting clouds and each carry their identifying attributes.\r\nA wax resist technique was employed in the decoration of this piece. The central panels were painted with wax before glazing to prevent the celadon glaze from adhering to those areas. Upon firing, the unglazed portions of the clay body burned a bright rust color due to iron compounds in the clay.", "web_url": "https://collections.artsmia.org/art/157", "img_url": "https://6.api.artsmia.org/157.jpg", "submit_time": "2023-04-11 13:11:01"},
        {"id": "157", "title": "Vase with the Eight Daoist Immortals", "dated": "c. 1300", "artist": "", "role": "Artist", "department": "Asian Art", "medium": "Longquan ware Porcelain with celadon glaze over impressed designs", "country": "China", "description": "Longquan ware; celadon glaze with 8 unglazed cartouches carved with immortals; floral cartouches above and below each immortal; low foot, narrow mouth", "comments": "This ovoid vase has an octagonal cross section and each of the eight sides comprising the vessel is decorated with molded recessed panels depicting one of the Eight Daoist Immortals amidst two floral sprays. The images of the immortals are shown standing on drifting clouds and each carry their identifying attributes.\r\nA wax resist technique was employed in the decoration of this piece. The central panels were painted with wax before glazing to prevent the celadon glaze from adhering to those areas. Upon firing, the unglazed portions of the clay body burned a bright rust color due to iron compounds in the clay.", "web_url": "https://collections.artsmia.org/art/157", "img_url": "https://6.api.artsmia.org/157.jpg", "submit_time": "2023-04-11 13:11:01"},
        {"id": "157", "title": "Vase with the Eight Daoist Immortals", "dated": "c. 1300", "artist": "", "role": "Artist", "department": "Asian Art", "medium": "Longquan ware Porcelain with celadon glaze over impressed designs", "country": "China", "description": "Longquan ware; celadon glaze with 8 unglazed cartouches carved with immortals; floral cartouches above and below each immortal; low foot, narrow mouth", "comments": "This ovoid vase has an octagonal cross section and each of the eight sides comprising the vessel is decorated with molded recessed panels depicting one of the Eight Daoist Immortals amidst two floral sprays. The images of the immortals are shown standing on drifting clouds and each carry their identifying attributes.\r\nA wax resist technique was employed in the decoration of this piece. The central panels were painted with wax before glazing to prevent the celadon glaze from adhering to those areas. Upon firing, the unglazed portions of the clay body burned a bright rust color due to iron compounds in the clay.", "web_url": "https://collections.artsmia.org/art/157", "img_url": "https://6.api.artsmia.org/157.jpg", "submit_time": "2023-04-11 13:11:01"},
        {"id": "157", "title": "Vase with the Eight Daoist Immortals", "dated": "c. 1300", "artist": "", "role": "Artist", "department": "Asian Art", "medium": "Longquan ware Porcelain with celadon glaze over impressed designs", "country": "China", "description": "Longquan ware; celadon glaze with 8 unglazed cartouches carved with immortals; floral cartouches above and below each immortal; low foot, narrow mouth", "comments": "This ovoid vase has an octagonal cross section and each of the eight sides comprising the vessel is decorated with molded recessed panels depicting one of the Eight Daoist Immortals amidst two floral sprays. The images of the immortals are shown standing on drifting clouds and each carry their identifying attributes.\r\nA wax resist technique was employed in the decoration of this piece. The central panels were painted with wax before glazing to prevent the celadon glaze from adhering to those areas. Upon firing, the unglazed portions of the clay body burned a bright rust color due to iron compounds in the clay.", "web_url": "https://collections.artsmia.org/art/157", "img_url": "https://6.api.artsmia.org/157.jpg", "submit_time": "2023-04-11 13:11:01"},
        {"id": "157", "title": "Vase with the Eight Daoist Immortals", "dated": "c. 1300", "artist": "", "role": "Artist", "department": "Asian Art", "medium": "Longquan ware Porcelain with celadon glaze over impressed designs", "country": "China", "description": "Longquan ware; celadon glaze with 8 unglazed cartouches carved with immortals; floral cartouches above and below each immortal; low foot, narrow mouth", "comments": "This ovoid vase has an octagonal cross section and each of the eight sides comprising the vessel is decorated with molded recessed panels depicting one of the Eight Daoist Immortals amidst two floral sprays. The images of the immortals are shown standing on drifting clouds and each carry their identifying attributes.\r\nA wax resist technique was employed in the decoration of this piece. The central panels were painted with wax before glazing to prevent the celadon glaze from adhering to those areas. Upon firing, the unglazed portions of the clay body burned a bright rust color due to iron compounds in the clay.", "web_url": "https://collections.artsmia.org/art/157", "img_url": "https://6.api.artsmia.org/157.jpg", "submit_time": "2023-04-11 13:11:01"},
        {"id": "157", "title": "Vase with the Eight Daoist Immortals", "dated": "c. 1300", "artist": "", "role": "Artist", "department": "Asian Art", "medium": "Longquan ware Porcelain with celadon glaze over impressed designs", "country": "China", "description": "Longquan ware; celadon glaze with 8 unglazed cartouches carved with immortals; floral cartouches above and below each immortal; low foot, narrow mouth", "comments": "This ovoid vase has an octagonal cross section and each of the eight sides comprising the vessel is decorated with molded recessed panels depicting one of the Eight Daoist Immortals amidst two floral sprays. The images of the immortals are shown standing on drifting clouds and each carry their identifying attributes.\r\nA wax resist technique was employed in the decoration of this piece. The central panels were painted with wax before glazing to prevent the celadon glaze from adhering to those areas. Upon firing, the unglazed portions of the clay body burned a bright rust color due to iron compounds in the clay.", "web_url": "https://collections.artsmia.org/art/157", "img_url": "https://6.api.artsmia.org/157.jpg", "submit_time": "2023-04-11 13:11:01"},
      ],
    };
  },
  created() {
    this.load()
  },
};
</script>

<style scoped>

.index-board-item {
  float: left;
  width: 249px;
  height: 400px;
  box-shadow: 0 0 1px #4fc08d;
  padding: 20px;
  margin-right: 34px;
  margin-bottom: 80px;
}
.index-board-item h2 {
  font-size: 18px;
  font-weight: bold;
  color: #000;
  margin-bottom: 15px;
}

.index-board-button {
  margin-top: 15px;
  margin-left: 80px;
}

.button {
  background: #4fc08d;
  color: #fff;
  display: inline-block;
  padding: 10px 20px;
  cursor: pointer;
}
</style>